# Generated by Django 3.0.5 on 2020-05-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0002_auto_20200503_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneinfo',
            old_name='phoneInfo',
            new_name='phoneNumber',
        ),
    ]
