# Generated by Django 3.0.5 on 2020-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0003_auto_20200503_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
