# Generated by Django 3.0.5 on 2020-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0004_skillsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsinfo',
            name='skillimg',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
